server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    username: root
    password: z4203226321185
    url: jdbc:mysql://localhost:3306/rsi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.softwaredemo.pojo
  mapper-locations: classpath:mapper/*.xml